'use strict';

function buildProposalTemplate(title) {
  const lines = [
    `# Proposal: ${title}`,
    '',
    '## Background / Problem',
    '<1-2 句话说明问题或机会>',
    '',
    '## Goals',
    '- <目标 1>',
    '- <目标 2>',
    '',
    '## Non-Goals',
    '- <非目标 1>',
    '- <非目标 2>',
    '',
    '## What Changes',
    '- <变更点 1>',
    '- <变更点 2>',
    '',
    '## Impact',
    '- 影响规范：<capability-1>, <capability-2>',
    '- 影响代码：<path-1>, <path-2>',
    '- 风险：<risk-1>, <risk-2>',
    '',
    '## Rollout',
    '- <步骤 1>',
    '- <步骤 2>',
    '',
  ];

  return lines.join('\n');
}

function buildDesignTemplate(title) {
  const lines = [
    `# Design: ${title}`,
    '',
    '## Context',
    '<背景、约束、利益相关方>',
    '',
    '## Goals / Non-Goals',
    '- 目标：<目标 1>, <目标 2>',
    '- 非目标：<非目标 1>, <非目标 2>',
    '',
    '## Decisions',
    '- 决策：<做什么 + 为什么>',
    '- 备选方案：<方案与取舍>',
    '',
    '## Risks',
    '- <风险 1> -> <应对>',
    '- <风险 2> -> <应对>',
    '',
    '## Migration Plan',
    '1) <步骤 1>',
    '2) <步骤 2>',
    '',
    '## Open Questions',
    '- <问题 1>',
    '- <问题 2>',
    '',
  ];

  return lines.join('\n');
}

function buildTasksTemplate(title, changeId, createdDate) {
  const lines = [
    `# Tasks: ${title}`,
    '',
    `**Change ID**: ${changeId}`,
    `**Created**: ${createdDate}`,
    '**Status**: pending',
    '',
    '---',
    '',
    '## Overview',
    '',
    '**Total Tasks**: 0',
    '**Estimated Time**: 0-0 分钟',
    '',
    '**Task Groups**:',
    '- Phase 1: 规划 (0 个任务)',
    '- Phase 2: 实现 (0 个任务)',
    '- Phase 3: 验证 (0 个任务)',
    '- Phase 4: 回滚 (0 个任务)',
    '',
    '---',
    '',
    '## Phase 1: 规划',
    '',
    '### 范围与策略',
    '',
    '#### 1.1 Confirm scope and dependencies',
    '',
    '**Description**: <需要确认的内容>',
    '**Files**: <仓库相对路径或 N/A>',
    '**Input**: proposal.md',
    '**Output**: design.md 更新',
    '',
    '#### 1.2 Confirm verification strategy',
    '',
    '**Description**: <验证、指标、验收标准>',
    '**Files**: <仓库相对路径或 N/A>',
    '**Input**: design.md',
    '**Output**: 验证任务',
    '',
    '## Phase 2: 实现',
    '',
    '### 核心变更',
    '',
    '#### 2.1 <task-title>',
    '',
    '**Description**: <任务描述>',
    '**Files**: <仓库相对路径>',
    '**Input**: <设计文档引用>',
    '**Output**: <代码变更>',
    '',
    '## Phase 3: 验证',
    '',
    '### 验证与校验',
    '',
    '#### 3.1 <task-title>',
    '',
    '**Description**: <验证动作>',
    '**Files**: <仓库相对路径>',
    '**Input**: <实现结果>',
    '**Output**: <验证证据>',
    '',
    '## Phase 4: 回滚',
    '',
    '### 回滚方案',
    '',
    '#### 4.1 <task-title>',
    '',
    '**Description**: <回滚步骤>',
    '**Files**: <仓库相对路径>',
    '**Input**: <失败场景>',
    '**Output**: <恢复状态>',
    '',
  ];

  return lines.join('\n');
}

module.exports = {
  buildProposalTemplate,
  buildDesignTemplate,
  buildTasksTemplate,
};
